### ISSUE TITLE
SARIF file generated and uploaded but no altert appears in GitHub

### ISSUE THREAD

**Issue by cschreib** [microsoft/msvc-code-analysis-action#10]
Hello! I have set up this action for my repository, and it is now running end-to-end. I can see the generated SARIF file as an artifact, and see that it contains some warnings: https://github.com/cschreib/lxgui/actions/runs/1393457069

The action step "Upload SARIF to GitHub" completes successfully, however no security alert shows up in GitHub. I also have CodeQL setup, and this works correctly. 

As recommended [here](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github) (and seeing what was done for CodeQL), I tried adding the following to the msvc action job, in case it was a permission issue:
```yml
    permissions:
      security-events: write
      actions: read
      contents: read
```
but this didn't help. Am I missing something?
